# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: VSTest@2
  inputs:
    testSelector: 'testPlan'
    testPlan: '4'
    testSuite: |
      {

        "id": 5,

        "name": "testapp",

        "plan": {

          "id": "4",

          "name": "4"

        },

        "testCaseCount": 0,

        "inheritDefaultConfigurations": false,

        "lastUpdatedDate": "0001-01-01T00:00:00",

        "text": "testapp"

      }
    testConfiguration: '4'
    searchFolder: '$(System.DefaultWorkingDirectory)/test.js'
    publishRunAttachments: false
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
